const MAX_POINTS=60;const history={cpu:[],gpu:[],memory:[],disk:[]};let paused=false;let failures=0;const $=id=>document.getElementById(id);const clamp=n=>Math.max(0,Math.min(100,Number(n)||0));
function bytes(value,rate=false){if(value===null||value===undefined)return"—";const units=["B","KB","MB","GB","TB"];let n=Number(value),i=0;while(Math.abs(n)>=1024&&i<units.length-1){n/=1024;i++}const digits=n>=100?0:n>=10?1:2;return`${n.toFixed(digits)} ${units[i]}`}
function duration(seconds){const d=Math.floor(seconds/86400),h=Math.floor(seconds%86400/3600),m=Math.floor(seconds%3600/60);return d?`${d}天 ${h}小时`:h?`${h}小时 ${m}分`:`${m}分钟`}
function colorFor(value,base){return value>=90?"#ff6b68":value>=75?"#ffad5c":base}
function setMetric(name,value,base){const v=value===null||value===undefined?null:clamp(value);$(name+"Value").textContent=v===null?"—":Math.round(v);const bar=$(name+"Bar");bar.style.width=(v||0)+"%";bar.style.background=colorFor(v||0,base)}
function push(key,value){history[key].push(value===null?null:Number(value));if(history[key].length>MAX_POINTS)history[key].shift()}
function drawSpark(id,data,color){const canvas=$(id),box=canvas.getBoundingClientRect(),dpr=window.devicePixelRatio||1;if(!box.width)return;canvas.width=box.width*dpr;canvas.height=box.height*dpr;const ctx=canvas.getContext("2d");ctx.scale(dpr,dpr);const w=box.width,h=box.height;ctx.clearRect(0,0,w,h);if(data.length<2)return;ctx.beginPath();data.forEach((v,i)=>{const x=i/(MAX_POINTS-1)*w,y=h-(Number(v)||0)/100*h;i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.lineTo((data.length-1)/(MAX_POINTS-1)*w,h);ctx.lineTo(0,h);ctx.closePath();const grad=ctx.createLinearGradient(0,0,0,h);grad.addColorStop(0,color+"45");grad.addColorStop(1,color+"00");ctx.fillStyle=grad;ctx.fill();ctx.beginPath();data.forEach((v,i)=>{const x=i/(MAX_POINTS-1)*w,y=h-(Number(v)||0)/100*h;i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.strokeStyle=color;ctx.lineWidth=1.5;ctx.stroke()}
function drawMain(){const canvas=$("mainChart"),box=canvas.getBoundingClientRect(),dpr=window.devicePixelRatio||1;if(!box.width)return;canvas.width=box.width*dpr;canvas.height=box.height*dpr;const ctx=canvas.getContext("2d");ctx.scale(dpr,dpr);const w=box.width,h=box.height,pad=8;ctx.clearRect(0,0,w,h);ctx.strokeStyle="rgba(255,255,255,.055)";ctx.lineWidth=1;ctx.font="10px Segoe UI";ctx.fillStyle="#65736f";[0,25,50,75,100].forEach(v=>{const y=pad+(100-v)/100*(h-pad*2);ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke();if(v>0)ctx.fillText(v+"%",4,y-4)});[[history.cpu,"#59e1d0"],[history.gpu,"#a58cff"],[history.memory,"#b6ef5b"]].forEach(([data,color])=>{ctx.beginPath();let started=false;data.forEach((v,i)=>{if(v===null)return;const x=i/(MAX_POINTS-1)*w,y=pad+(100-v)/100*(h-pad*2);started?ctx.lineTo(x,y):(ctx.moveTo(x,y),started=true)});ctx.strokeStyle=color;ctx.lineWidth=2;ctx.lineJoin="round";ctx.stroke()})}
function renderPrograms(target,rows,mode){const max=Math.max(...rows.map(r=>mode==="cpu"?r.cpu_percent:r.memory_bytes),1);$(target).replaceChildren(...rows.map((row,index)=>{const el=document.createElement("div");el.className="process-row";const value=mode==="cpu"?`${row.cpu_percent.toFixed(1)}%`:bytes(row.memory_bytes);const tail=mode==="cpu"?bytes(row.memory_bytes):`${row.instances} 个`;const ratio=(mode==="cpu"?row.cpu_percent:row.memory_bytes)/max*100;const initial=(row.name[0]||"?").toUpperCase();el.innerHTML=`<div class="process-name"><i>${initial.replace(/[<&]/g,"")}</i><div><strong></strong><small>${row.instances} 个实例 · PID ${row.pids.join(", ")}</small><div class="mini-bar"><i style="width:${ratio}%"></i></div></div></div><span>${value}</span><span>${tail}</span>`;el.querySelector("strong").textContent=row.name;return el}))}
function update(data){setMetric("cpu",data.cpu.percent,"#59e1d0");setMetric("gpu",data.gpu.percent,"#a58cff");setMetric("memory",data.memory.percent,"#b6ef5b");setMetric("disk",data.disk.percent,"#ffad5c");$("cpuMeta").textContent=`${data.cpu.logical_cores} 线程${data.cpu.frequency_mhz?` · ${data.cpu.frequency_mhz} MHz`:""}`;$("gpuMeta").textContent=data.gpu.temperature_c!==null?`${data.gpu.temperature_c}°C`:data.gpu.available?"已连接":"不可用";$("memoryMeta").textContent=`${bytes(data.memory.used)} / ${bytes(data.memory.total)}`;$("diskMeta").textContent=`剩余 ${bytes(data.disk.free)}`;$("hostName").textContent=data.host.name;$("uptime").textContent=`运行时间 ${duration(data.host.uptime_seconds)}`;$("updatedAt").textContent=new Date(data.timestamp).toLocaleTimeString("zh-CN",{hour12:false});$("netDown").textContent=bytes(data.network.download_bps);$("netUp").textContent=bytes(data.network.upload_bps);$("diskRead").textContent=bytes(data.disk.read_bps);$("diskWrite").textContent=bytes(data.disk.write_bps);$("gpuName").textContent=data.gpu.name;$("gpuDetail").textContent=data.gpu.memory_total?`显存 ${bytes(data.gpu.memory_used)} / ${bytes(data.gpu.memory_total)}`:data.gpu.source==="windows-performance-counter"?"Windows 性能计数器":"详细指标不可用";$("processCount").textContent=`${data.processes.count} 个进程`;renderPrograms("topCpu",data.processes.top_cpu,"cpu");renderPrograms("topMemory",data.processes.top_memory,"memory");const peak=Math.max(data.cpu.percent||0,data.memory.percent||0,data.gpu.percent||0,data.disk.percent||0);$("healthText").textContent=peak>=90?"压力较高":peak>=75?"负载上升":"运行平稳";$("healthText").style.color=colorFor(peak,"#59e1d0");push("cpu",data.cpu.percent);push("gpu",data.gpu.percent);push("memory",data.memory.percent);push("disk",data.disk.percent);drawSpark("cpuSpark",history.cpu,"#59e1d0");drawSpark("gpuSpark",history.gpu,"#a58cff");drawSpark("memorySpark",history.memory,"#b6ef5b");drawSpark("diskSpark",history.disk,"#ffad5c");drawMain()}
async function refresh(){if(paused)return;try{const response=await fetch("/api/metrics",{cache:"no-store"});if(!response.ok)throw new Error(`HTTP ${response.status}`);update(await response.json());failures=0;$("errorToast").classList.remove("show")}catch(error){failures++;if(failures>=2){$("errorToast").textContent="暂时无法读取系统数据，正在自动重试";$("errorToast").classList.add("show")}}}
$("pauseButton").addEventListener("click",()=>{paused=!paused;$("pauseButton").textContent=paused?"继续":"暂停";$("updatedAt").textContent=paused?"已暂停":"恢复中";if(!paused)refresh()});window.addEventListener("resize",()=>{drawMain();drawSpark("cpuSpark",history.cpu,"#59e1d0");drawSpark("gpuSpark",history.gpu,"#a58cff");drawSpark("memorySpark",history.memory,"#b6ef5b");drawSpark("diskSpark",history.disk,"#ffad5c")});refresh();setInterval(refresh,1000);

